version: "3.8"

services:
  web-backend:
    container_name: web-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "pipenv run python /code/manage.py makemigrations &&
             pipenv run python /code/manage.py migrate &&
             pipenv run python /code/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - DJANGO_DEVELOPMENT=yes
    volumes:
      - .:/code
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    container_name: db
    image: "postgres:13.6"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

volumes:
  postgres_data:
