---
version: "3.8"

services:
  db:
    container_name: lifter-api-db
    image: "postgres:13.6"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    restart: always

  # backend:
  #   container_name: lifter-api-backend
  #   build: ./backend
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   restart: always
  #   ports:
  #     - "${APP_PORT:-8000}:8000"
  #   volumes:
  #     - ./backend:/code/
  #
  # frontend:
  #   container_name: lifter-api-frontend
  #   build: ./frontend
  #   depends_on:
  #     - backend
  #   env_file:
  #     - .env
  #   restart: always
  #   ports:
  #     - "${FRONTEND_APP_PORT:-3000}:3000"
  #   volumes:
  #     - ./frontend:/code/

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
