version: "3.8"

services:
  db:
    container_name: lifter-api-db
    image: "postgres:13.6"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql restart: always

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
