---
site_name: Lifter API
site_url: https://WeightliftingNZ.github.io/lifter-api
nav:
  - Home: index.md
theme:
  name: material
  palette:
    - media: "(prefers-color-schema: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-schema: light)"
      scheme: default
      primary: black
      accent: light-blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
watch:
  - backend
plugins:
  - search
