---
name: Build Frontend

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build_frontend:
    name: Build, run and test frontend
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: install-node
        name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - id: run-npm
        name: Run npm ci, build and test
        run: |
          cd frontend
          npm ci
          npm run build --if-present
          npm test --updateSnapshot
